name: Pull request checks
on:
  pull_request:
    branches:
      - develop
      - release/**
      - hotfix/**

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Unit tests
        run: ./gradlew test

